import type { QuizFrage, QuizModul, Schwierigkeit } from '@/types'

export type { QuizFrage, QuizModul }

export const QUIZ_MODUL_LABEL: Record<QuizModul, string> = {
  gespraechsphasen: 'Gesprächsphasen',
  reaktionen:       'Reaktionen auf Elternverhalten',
  rechtswissen:     'Rechtswissen',
  gfk:              'Klärende Kommunikation',
  vorbereitung:     'Vorbereitung',
  koerpersignale:   'Körpersignale',
  massnahmen:       'Maßnahmen & Folgeschritte',
}

export const QUIZ_FRAGEN: QuizFrage[] = [
  // ── Gesprächsphasen ─────────────────────────────────────────────────────────
  {
    id: 'gp-01',
    modul: 'gespraechsphasen',
    schwierigkeit: 'ruhige-see',
    frage: 'In welcher Gesprächsphase sollten konkrete Vereinbarungen (wer macht was bis wann?) getroffen werden?',
    antworten: ['Begrüßung & Ankommen', 'Dialog & Zuhören', 'Ergebnis & Vereinbarungen', 'Themeneinführung'],
    korrektIndex: 2,
    erklaerung: 'Die Ergebnis-Phase dient dazu, das Gespräch in klare, umsetzbare Schritte zu überführen. Ohne konkrete Vereinbarungen bleibt vieles in der Luft.',
  },
  {
    id: 'gp-02',
    modul: 'gespraechsphasen',
    schwierigkeit: 'ruhige-see',
    frage: 'Was ist das Hauptziel der Themeneinführungs-Phase?',
    antworten: [
      'Eltern von der eigenen Sicht zu überzeugen',
      'Den Gesprächsanlass klar und wertfrei benennen',
      'Sofort Lösungsvorschläge machen',
      'Die eigene Dokumentation vorstellen',
    ],
    korrektIndex: 1,
    erklaerung: 'Die Themeneinführung soll Klarheit schaffen ohne Vorwurf. Wertfreies Benennen des Anlasses gibt Eltern die Möglichkeit, offen in das Gespräch zu gehen.',
  },
  {
    id: 'gp-03',
    modul: 'gespraechsphasen',
    schwierigkeit: 'gegenwind',
    frage: 'Eltern unterbrechen Sie mehrfach mit eigenen Kommentaren. In welcher Phase ist das am häufigsten problematisch?',
    antworten: ['Begrüßung', 'Themeneinführung', 'Dialog & Zuhören', 'Abschluss'],
    korrektIndex: 2,
    erklaerung: 'Im Dialog sind gegenseitiges Zuhören und Respekt entscheidend. Unterbrechungen hier stören den Vertrauensaufbau. Eine ruhige, nicht konfrontative Reaktion ("Ich höre Sie – darf ich kurz zu Ende sprechen?") ist meist wirksam.',
  },
  {
    id: 'gp-04',
    modul: 'gespraechsphasen',
    schwierigkeit: 'gewitterfront',
    frage: 'Das Gespräch ist emotional eskaliert. Welche Phase sollten Sie jetzt bewusst einleiten?',
    antworten: [
      'Sofort zur Ergebnis-Phase übergehen',
      'Zum Dialog & Zuhören zurückkehren und das Gesagte kurz in eigenen Worten spiegeln',
      'Das Gespräch abbrechen und auf ein neues Treffen vertagen',
      'Die eigene Position klarer formulieren',
    ],
    korrektIndex: 1,
    erklaerung: 'Bei Eskalation helfen aktives Zuhören und das Gesagte kurz in eigenen Worten wiederholen: Eltern fühlen sich gehört, Spannung nimmt ab. Erst dann können Ergebnisse nachhaltig erarbeitet werden.',
  },

  // ── Reaktionen auf Elternverhalten ──────────────────────────────────────────
  {
    id: 're-01',
    modul: 'reaktionen',
    schwierigkeit: 'ruhige-see',
    frage: 'Ein Elternteil sagt: "Zuhause ist er aber ganz anders!" Was ist die beste erste Reaktion?',
    antworten: [
      'Widersprechen und auf eigene Beobachtungen bestehen',
      'Die Elternperspektive anerkennen und nachfragen',
      'Das Thema wechseln',
      'Zahlen und Fakten präsentieren',
    ],
    korrektIndex: 1,
    erklaerung: 'Die Aussage signalisiert defensives Verhalten. Anerkennen ("Das kann ich gut verstehen, dass er zuhause anders ist") und neugieriges Nachfragen öffnet Eltern mehr als Gegenbeweis.',
  },
  {
    id: 're-02',
    modul: 'reaktionen',
    schwierigkeit: 'gegenwind',
    frage: 'Eltern werden aggressiver und machen Sie persönlich verantwortlich. Was hilft in diesem Moment am meisten?',
    antworten: [
      'Ruhig bleiben und Deeskalationsformeln einsetzen („Ich höre, dass Sie das sehr belastet …")',
      'Sofort sachliche Gegenargumente nennen',
      'Das Gespräch für beendet erklären',
      'Die Schulleitung zum Gespräch hinzubitten',
    ],
    korrektIndex: 0,
    erklaerung: 'Bei Aggression gilt: Ruhe bewahren und Verständnis zeigen, ohne zu kapitulieren. "Ich höre, dass Sie sich Sorgen machen" ist kein Schuldeingeständnis, aber nimmt Druck aus der Situation.',
  },
  {
    id: 're-03',
    modul: 'reaktionen',
    schwierigkeit: 'gegenwind',
    frage: 'Eine Mutter weint und das Gespräch droht zum Seelsorgegespräch zu werden. Was tun?',
    antworten: [
      'Mitgefühl zeigen und dann behutsam den Fokus auf das Kind zurücklenken',
      'Das Gespräch sofort verschieben',
      'Zur Sache kommen und die Emotionen übersehen',
      'Ihr anbieten, alles später per Mail zu klären',
    ],
    korrektIndex: 0,
    erklaerung: 'Mitgefühl ist wichtig – aber die eigene Rolle darf nicht wechseln. Eine ruhige Rückführung ("Ich merke, dass das gerade viel ist. Darf ich kurz zu Sophie kommen – was braucht sie jetzt am meisten?") hilft.',
  },
  {
    id: 're-04',
    modul: 'reaktionen',
    schwierigkeit: 'gewitterfront',
    frage: 'Eltern fordern lautstark eine Notenänderung und drohen mit Klage. Was ist jetzt die richtige Reaktion?',
    antworten: [
      'Klar und freundlich Grenzen setzen: "Eine Notenänderung liegt nicht in meinem Ermessen – das erkläre ich Ihnen gerne."',
      'Nachgeben, um die Situation zu beruhigen',
      'Sofort die Schulleitung anrufen',
      'Das Gespräch wortlos beenden',
    ],
    korrektIndex: 0,
    erklaerung: 'Grenzen setzen, ohne zu eskalieren: Die Forderung ernst nehmen, aber klar kommunizieren, was möglich ist und was nicht. Keine Versprechungen, kein Nachgeben unter Druck.',
  },
  {
    id: 're-05',
    modul: 'reaktionen',
    schwierigkeit: 'gewitterfront',
    frage: 'Ein schweigendes Elternteil gibt nur Einsilber-Antworten. Wie locken Sie es aus der Reserve?',
    antworten: [
      'Mit offenen Fragen und Pausen: "Was ist Ihnen bei diesem Thema besonders wichtig?"',
      'Mehr und mehr erklären, bis eine Reaktion kommt',
      'Das Schweigen als Zustimmung werten',
      'Die Fragen schriftlich mitgeben und später per Mail beantworten lassen',
    ],
    korrektIndex: 0,
    erklaerung: 'Offene Fragen ohne Druck sind der Schlüssel. Pausen aushalten. Das Schweigen könnte Überforderung, Sprachbarriere oder Angst signalisieren – Neugier statt Konfrontation.',
  },

  // ── Rechtswissen ─────────────────────────────────────────────────────────────
  {
    id: 'rw-01',
    modul: 'rechtswissen',
    schwierigkeit: 'ruhige-see',
    frage: 'Was regelt § 8a SGB VIII für Lehrkräfte?',
    antworten: [
      'Das Recht, Eltern Hausbesuche zu machen',
      'Die Pflicht, bei gewichtigen Anhaltspunkten für Kindeswohlgefährdung tätig zu werden',
      'Die Möglichkeit, Noten anzufechten',
      'Den Datenschutz bei Elterngesprächen',
    ],
    korrektIndex: 1,
    erklaerung: '§ 8a SGB VIII verpflichtet Fachkräfte, bei gewichtigen Anhaltspunkten für Kindeswohlgefährdung eine Gefährdungseinschätzung vorzunehmen und ggf. das Jugendamt einzuschalten.',
  },
  {
    id: 'rw-02',
    modul: 'rechtswissen',
    schwierigkeit: 'gegenwind',
    frage: 'Was dürfen Sie im Elterngespräch einem Elternteil über das Gespräch mit dem anderen Elternteil mitteilen – bei getrennt lebenden Eltern?',
    antworten: [
      'Alles, da beide sorgeberechtigt sind',
      'Nichts, da Datenschutz gilt',
      'Grundsätzlich beide informieren, aber keine Details aus Einzelgesprächen weitergeben',
      'Nur was das Kind explizit erlaubt hat',
    ],
    korrektIndex: 2,
    erklaerung: 'Beide sorgeberechtigten Elternteile haben Anspruch auf schulische Informationen. Inhalte aus Einzelgesprächen, insbesondere wenn ein Elternteil nicht anwesend war, sollten aber mit Bedacht kommuniziert werden.',
  },
  {
    id: 'rw-03',
    modul: 'rechtswissen',
    schwierigkeit: 'gegenwind',
    frage: 'Was muss in einem Gesprächsprotokoll dokumentiert werden?',
    antworten: [
      'Nur die Noten des Kindes',
      'Datum, Teilnehmende, Gesprächsthemen, Vereinbarungen, nächste Schritte',
      'Der vollständige Gesprächsverlauf wortwörtlich',
      'Nur Maßnahmen, die die Schule ergreift',
    ],
    korrektIndex: 1,
    erklaerung: 'Ein gutes Protokoll enthält Rahmendaten (wann, wer), das Thema, besprochene Punkte, Vereinbarungen und Folgeschritte. Es schützt alle Beteiligten und schafft Verbindlichkeit.',
  },
  {
    id: 'rw-04',
    modul: 'rechtswissen',
    schwierigkeit: 'gewitterfront',
    frage: 'Eltern verlangen Einsicht in die Notizen anderer Schüler aus Ihrem Unterricht. Was gilt?',
    antworten: [
      'Eltern haben grundsätzlich das Recht auf alle Unterlagen',
      'Datenschutz schützt Daten anderer Schüler – Einsicht in Fremdunterlagen ist nicht zulässig',
      'Sie dürfen alles zeigen, was Sie selbst notiert haben',
      'Das ist nur mit Genehmigung der Schulleitung möglich',
    ],
    korrektIndex: 1,
    erklaerung: 'Datenschutz (DSGVO + Schulrecht) schützt personenbezogene Daten anderer Schüler. Eltern haben Einsicht in die Leistungsdaten ihres eigenen Kindes – nicht in die anderer.',
  },

  // ── Klärende Kommunikation ────────────────────────────────────────────────────
  {
    id: 'gfk-01',
    modul: 'gfk',
    schwierigkeit: 'ruhige-see',
    frage: 'Was beschreibt, was in einem Gespräch konkret wahrgenommen wurde – ohne Bewertung?',
    antworten: [
      '"Max ist faul."',
      '"Max hat in den letzten drei Wochen keine Hausaufgaben abgegeben."',
      '"Max scheint sich nicht zu kümmern."',
      '"Max will Ihre Autorität nicht anerkennen."',
    ],
    korrektIndex: 1,
    erklaerung: 'Eine konkrete Beschreibung nennt, was tatsächlich passiert ist – ohne Bewertung oder Interpretation. "Keine Hausaufgaben abgegeben" ist beobachtbar und nachvollziehbar. "Faul" oder "kümmert sich nicht" sind Urteile.',
  },
  {
    id: 'gfk-02',
    modul: 'gfk',
    schwierigkeit: 'ruhige-see',
    frage: 'Welche der folgenden Aussagen formuliert eine klare, einladende Bitte?',
    antworten: [
      '"Sie müssen Lena jeden Abend beim Lernen helfen."',
      '"Ich bitte Sie, Lena abends 20 Minuten beim Lernen zu begleiten."',
      '"Lena braucht mehr Unterstützung von zuhause."',
      '"Das liegt in Ihrer Verantwortung als Eltern."',
    ],
    korrektIndex: 1,
    erklaerung: 'Eine klare Bitte ist konkret, positiv formuliert und offen für ein Nein. "Ich bitte Sie, X zu tun" schafft Klarheit ohne Druck – anders als "Sie müssen" oder vage Erwartungen.',
  },
  {
    id: 'gfk-03',
    modul: 'gfk',
    schwierigkeit: 'gegenwind',
    frage: 'Eltern sagen: "Ihr Unterricht ist langweilig – kein Wunder, dass Tobias nichts lernt." Welche Reaktion wäre hier gesprächsfördernd?',
    antworten: [
      'Zurückweisen: "Das stimmt nicht, mein Unterricht ist gut vorbereitet."',
      'Anerkennen und hinter die Aussage schauen: "Ich höre, dass Sie sich Sorgen machen, wie Tobias den Unterricht erlebt."',
      'Keine Reaktion zeigen',
      'Die Eltern darauf hinweisen, dass sie Tobias selbst befragen sollen',
    ],
    korrektIndex: 1,
    erklaerung: 'Hinter einer Aussage wie dieser steckt oft eine echte Sorge. Das anzusprechen – statt sich zu verteidigen – öffnet das Gespräch und schafft Vertrauen.',
  },
  {
    id: 'gfk-04',
    modul: 'gfk',
    schwierigkeit: 'gewitterfront',
    frage: 'Welche Formulierung benennt klar, was sich die Lehrkraft für das Gespräch wünscht?',
    antworten: [
      '"Sie machen das immer falsch."',
      '"Ich brauche in diesem Gespräch, dass wir gemeinsam nach Lösungen für Jonas suchen."',
      '"Jonas braucht einfach mehr Disziplin."',
      '"Wir sind uns hier offensichtlich nicht einig."',
    ],
    korrektIndex: 1,
    erklaerung: 'In der Ich-Form lässt sich klar und ohne Vorwurf sagen, was man sich für das Gespräch wünscht. „Ich brauche …" schafft Transparenz und bleibt lösungsorientiert.',
  },

  // ── Körpersignale ─────────────────────────────────────────────────────────────
  {
    id: 'ks-q01',
    modul: 'koerpersignale',
    schwierigkeit: 'ruhige-see',
    frage: 'Was bedeutet es, wenn ein Elternteil Ihnen gegenüber konstant Blickkontakt hält, nickt und sich leicht vorbeugt?',
    antworten: [
      'Er oder sie stimmt allem zu, was Sie sagen.',
      'Er oder sie zeigt aktives Zuhören und Gesprächsbereitschaft.',
      'Er oder sie versucht, Sie unter Druck zu setzen.',
      'Er oder sie ist sehr nervös.',
    ],
    korrektIndex: 1,
    erklaerung: 'Blickkontakt, Nicken und Vorbeugen signalisieren aktives Zuhören und Offenheit – aber noch keine inhaltliche Zustimmung. Wichtig: Trotz kooperativer Körperhaltung weiterhin nachfragen, ob das Gesagte wirklich verstanden wurde.',
  },
  {
    id: 'ks-q02',
    modul: 'koerpersignale',
    schwierigkeit: 'ruhige-see',
    frage: 'Eltern lehnen sich beide zurück und die Antworten werden einsilbiger. Was signalisiert das?',
    antworten: [
      'Sie sind mit dem Gespräch zufrieden und entspannen sich.',
      'Zunehmende Abwehrhaltung – das Gespräch hat möglicherweise einen als bedrohlich empfundenen Punkt erreicht.',
      'Sie wollen das Gespräch bald beenden, weil sie einen anderen Termin haben.',
      'Das ist bedeutungslos – Körperhaltung und Gesprächsinhalt hängen nicht zusammen.',
    ],
    korrektIndex: 1,
    erklaerung: 'Rückwärtslehnen und Einsilbigkeit zusammen signalisieren Rückzug. Jetzt ist es sinnvoll, den Druck aus dem Gespräch zu nehmen: "Mir ist wichtig, dass wir heute gemeinsam zu einem guten Ergebnis kommen." Dann eine offene Frage stellen.',
  },
  {
    id: 'ks-q03',
    modul: 'koerpersignale',
    schwierigkeit: 'gegenwind',
    frage: 'Ein Vater beugt sich vor, spricht lauter und gestikuliert. Was ist die geeignete Reaktion als Lehrkraft?',
    antworten: [
      'Ebenfalls lauter werden, um Präsenz zu zeigen.',
      'Das Gespräch unterbrechen und die Schulleitung hinzuholen.',
      'Ruhig und langsam sprechen – der eigene Tonfall wirkt oft regulierend.',
      'Die Aussagen ignorieren und zum nächsten Thema übergehen.',
    ],
    korrektIndex: 2,
    erklaerung: 'Vorneigen und lauter werden zeigt hohes Erregungsniveau. Nicht spiegeln – das eskaliert. Stattdessen: Eigenes Sprechtempo und Lautstärke bewusst senken. "Ich höre, dass Ihnen das wichtig ist – darf ich kurz antworten?" gibt dem Gespräch Raum.',
  },
  {
    id: 'ks-q04',
    modul: 'koerpersignale',
    schwierigkeit: 'gewitterfront',
    frage: 'Eine Mutter lächelt häufig und nickt, macht aber kaum eigene Aussagen und weicht konkreten Fragen aus. Was tun?',
    antworten: [
      'Das Lächeln als Zustimmung werten und die Vereinbarungen festhalten.',
      'Das Gespräch abkürzen – sie ist offensichtlich einverstanden.',
      'Einfache, offene Fragen stellen und echte Pausen aushalten.',
      'Die Situation der Schulleitung melden, da das Verhalten verdächtig ist.',
    ],
    korrektIndex: 2,
    erklaerung: 'Lächeln ohne Inhalt kann soziale Höflichkeit, Unsicherheit oder eine Sprachbarriere signalisieren – keine echte Zustimmung. Konkrete, einfache offene Fragen stellen ("Was ist Ihnen heute besonders wichtig?") und Pausen wirklich aushalten, ohne sofort weiterzusprechen.',
  },

  // ── Vorbereitung ──────────────────────────────────────────────────────────────
  {
    id: 'vb-01',
    modul: 'vorbereitung',
    schwierigkeit: 'ruhige-see',
    frage: 'Was ist das wichtigste Element bei der Gesprächsvorbereitung?',
    antworten: [
      'Eine Liste aller Fehler des Kindes zusammenstellen',
      'Das Gesprächsziel definieren: Was soll am Ende anders sein?',
      'Sich auf Gegenargumente der Eltern vorbereiten',
      'Die letzte Klassenarbeit des Kindes dabei haben',
    ],
    korrektIndex: 1,
    erklaerung: 'Ohne klares Ziel verliert das Gespräch die Richtung. Das Ziel sollte konkret und lösungsorientiert sein – "Was soll nach dem Gespräch für das Kind besser sein?"',
  },
  {
    id: 'vb-02',
    modul: 'vorbereitung',
    schwierigkeit: 'gegenwind',
    frage: 'Wann sollte zusätzlich die Schulleitung oder Beratungslehrkraft hinzugezogen werden?',
    antworten: [
      'Bei jedem Elterngespräch',
      'Nur bei Scheidungssituationen',
      'Bei wiederholten Eskalationen, rechtlichen Androhungen oder Gefährdungshinweisen',
      'Wenn Eltern eine Notenänderung fordern',
    ],
    korrektIndex: 2,
    erklaerung: 'Schulleitung und Beratungslehrkraft sind keine Eskalationsstufe, sondern Ressourcen. Bei ernsteren Fällen – Eskalation, Rechtsandrohungen, Gefährdung – ist das Hinzuziehen professionell und angemessen.',
  },
  {
    id: 'vb-03',
    modul: 'vorbereitung',
    schwierigkeit: 'gegenwind',
    frage: 'Welches Setting ist für ein Elterngespräch am günstigsten?',
    antworten: [
      'Im Klassenzimmer am Lehrerpult',
      'Im Lehrerzimmer, während andere anwesend sind',
      'In einem ruhigen Raum mit Stühlen auf Augenhöhe',
      'In der Schulleitung, um Autorität zu signalisieren',
    ],
    korrektIndex: 2,
    erklaerung: 'Augenhöhe ist buchstäblich und symbolisch wichtig. Ein ruhiger, neutraler Raum ohne Rangsignale (kein Pult zwischen Lehrkraft und Eltern) fördert ein offenes Gespräch.',
  },

  // ── Maßnahmen & Folgeschritte ────────────────────────────────────────────────
  {
    id: 'mas-01',
    modul: 'massnahmen',
    schwierigkeit: 'ruhige-see',
    frage: 'Eine Schülerin kommt regelmäßig zu spät. Welche Maßnahme ist sofort und allein umsetzbar?',
    antworten: [
      'Schulleitung informieren',
      'Klare Regel für Verspätungen kommunizieren – mündlich und schriftlich',
      'Förderplan erstellen',
      'Jugendamt einschalten',
    ],
    korrektIndex: 1,
    erklaerung: 'Das Kommunizieren klarer Regeln ist eine niedrigschwellige Sofortmaßnahme, die die Lehrkraft allein umsetzen kann. Schulleitung und Jugendamt werden erst eingeschaltet, wenn einfachere Maßnahmen nicht wirken oder ein Gefährdungshinweis vorliegt.',
  },
  {
    id: 'mas-02',
    modul: 'massnahmen',
    schwierigkeit: 'ruhige-see',
    frage: 'Ein Schüler vergisst regelmäßig Hausaufgaben. Was ist der sinnvollste erste Schritt?',
    antworten: [
      'Eltern sofort anrufen',
      'Schulsozialdienst einschalten',
      'Ein Hausaufgaben-Heft einführen oder das bestehende prüfen',
      'Nachteilsausgleich beantragen',
    ],
    korrektIndex: 2,
    erklaerung: 'Ein Hausaufgaben-Heft ist die am wenigsten invasive Maßnahme mit der höchsten Wirkwahrscheinlichkeit. Erst wenn das nicht hilft, folgen weitere Schritte. Nachteilsausgleich gilt nur bei anerkannter Lernschwäche – nicht bei Vergesslichkeit.',
  },
  {
    id: 'mas-03',
    modul: 'massnahmen',
    schwierigkeit: 'ruhige-see',
    frage: 'Warum kann eine positive Nachricht an Eltern (kein Problem, nur ein Lob) sinnvoll sein?',
    antworten: [
      'Das ist rechtlich vorgeschrieben',
      'Es verändert die Beziehungsdynamik positiv und erleichtert spätere Problemgespräche',
      'Es ersetzt das Elterngespräch',
      'Das ist nur bei Problemkindern wichtig',
    ],
    korrektIndex: 1,
    erklaerung: 'Kontakt nur bei Problemen prägt das Bild, das Eltern von der Schule haben. Wer auch mal Positives rückmeldet, baut Vertrauen auf – und wird bei schwierigen Gesprächen als Partner wahrgenommen, nicht als Ankläger.',
  },
  {
    id: 'mas-04',
    modul: 'massnahmen',
    schwierigkeit: 'gegenwind',
    frage: 'Ein Elternteil signalisiert, dass zuhause kaum Unterstützung bei Hausaufgaben möglich ist. Welche Maßnahme ist realistisch und kooperativ?',
    antworten: [
      'Sofort den Schulpsychologischen Dienst einschalten',
      'Eine gemeinsame Absprache: Was können und wollen die Eltern realistisch leisten',
      'Das Kind darf vorerst keine Hausaufgaben bekommen',
      'Einen Förderplan erstellen',
    ],
    korrektIndex: 1,
    erklaerung: 'Eine ehrliche Absprache über Möglichkeiten und Grenzen der Eltern ist der erste kooperative Schritt. Hausaufgaben-Betreuung (OGS, Lerninstitut) könnte als ergänzende Empfehlung folgen. Ein Förderplan braucht eine anerkannte Lernschwäche als Grundlage.',
  },
  {
    id: 'mas-05',
    modul: 'massnahmen',
    schwierigkeit: 'gegenwind',
    frage: 'Wann sollte eine Klassenkonferenz einberufen werden?',
    antworten: [
      'Nach jedem Elterngespräch zur Information der Kollegen',
      'Wenn ein Problem mehrere Fächer betrifft und verschiedene Lehrkräfte unterschiedliche Wahrnehmungen haben',
      'Nur bei Gefährdungseinschätzung',
      'Immer vor einem schwierigen Elterngespräch',
    ],
    korrektIndex: 1,
    erklaerung: 'Die Klassenkonferenz bringt den gemeinsamen Blick aller Fachlehrkräfte ein – das ist besonders wertvoll, wenn ein Kind in einem Fach auffällig ist, in anderen aber nicht. Das klärt oft, ob es sich um ein fachspezifisches oder übergreifendes Problem handelt.',
  },
  {
    id: 'mas-06',
    modul: 'massnahmen',
    schwierigkeit: 'gegenwind',
    frage: 'Was gehört zu einer verbindlichen schriftlichen Vereinbarung mit Eltern?',
    antworten: [
      'Nur die Unterschrift der Lehrkraft genügt',
      'Eine Liste aller aktuellen Noten des Kindes',
      'Klare Formulierung, wer was bis wann tut – beide Seiten unterschreiben',
      'Ein rechtlich geprüftes Dokument vom Schulamt',
    ],
    korrektIndex: 2,
    erklaerung: 'Eine gute Vereinbarung ist klar, konkret und bilateral: wer tut was, bis wann, und wie wird es überprüft. Das schützt alle Beteiligten und schafft Verbindlichkeit – ohne dass es rechtlich aufwendig sein muss.',
  },
  {
    id: 'mas-07',
    modul: 'massnahmen',
    schwierigkeit: 'gegenwind',
    frage: 'Wann ist es besonders sinnvoll, den Schüler selbst in ein Gespräch mit Eltern und Lehrkraft einzubeziehen?',
    antworten: [
      'Immer – bei jedem Elterngespräch',
      'Nur bei Schülerinnen und Schülern ab Klasse 7',
      'Wenn das Kind zwischen Schule und Eltern eingeklemmt wirkt und eine eigene Stimme braucht',
      'Wenn die Eltern nicht kooperieren wollen',
    ],
    korrektIndex: 2,
    erklaerung: 'Das Dreiergespräch – Kind, Elternteil, Lehrkraft – ist besonders dann hilfreich, wenn das Kind in Loyalitätskonflikte gerät oder wenn seine Perspektive im Gespräch zwischen Erwachsenen unterzugehen droht. Es gibt dem Kind Handlungsfähigkeit.',
  },
  {
    id: 'mas-08',
    modul: 'massnahmen',
    schwierigkeit: 'gewitterfront',
    frage: 'Ein Kind kommt mehrfach mit unklaren blauen Flecken in die Schule. Welcher Ablauf entspricht § 8a SGB VIII?',
    antworten: [
      'Sofort das Jugendamt anrufen, ohne die Schulleitung zu informieren',
      'Beobachtungen dokumentieren, Schulleitung informieren, Risikoeinschätzung, ggf. Eltern informieren, bei dringendem Verdacht Meldung ans Jugendamt',
      'Die Eltern direkt konfrontieren und um sofortige Erklärung bitten',
      'Abwarten, ob sich die Situation wiederholt',
    ],
    korrektIndex: 1,
    erklaerung: '§ 8a SGB VIII sieht einen strukturierten Ablauf vor, der die Schule als Institution einbindet – nicht nur die einzelne Lehrkraft. Die Schulleitung muss immer einbezogen werden. Eltern werden informiert, außer wenn das Gespräch das Kind gefährden würde.',
  },
  {
    id: 'mas-09',
    modul: 'massnahmen',
    schwierigkeit: 'gewitterfront',
    frage: 'Ein Kind mit diagnostizierter LRS erhält keinen Nachteilsausgleich. Was muss die Lehrkraft veranlassen?',
    antworten: [
      'Die Note selbst anpassen, ohne Dokumentation',
      'Warten, bis die Eltern den Antrag stellen',
      'Den Nachteilsausgleich formal beantragen – die Regelungen sind bundeslandspezifisch',
      'Das Kind von der Prüfung befreien',
    ],
    korrektIndex: 2,
    erklaerung: 'Nachteilsausgleich (z. B. Zeitverlängerung oder alternative Aufgabenformate) muss formal beantragt werden und basiert auf der Diagnose. Die genauen Regelungen unterscheiden sich je nach Bundesland erheblich. Eigenmächtiges Anpassen ohne Antrag schützt die Lehrkraft rechtlich nicht.',
  },
  {
    id: 'mas-10',
    modul: 'massnahmen',
    schwierigkeit: 'gewitterfront',
    frage: 'Eine Mutter ist offensichtlich am Limit – sie weint, schildert eigene Belastungen, das Gespräch droht zum Seelsorgegespräch zu werden. Was ist die richtige Reaktion?',
    antworten: [
      'Das Gespräch sofort abbrechen und einen neuen Termin vereinbaren',
      'Mitgefühl zeigen, ohne die Rolle zu wechseln – und behutsam zur Ausgangsfrage des Gesprächs zurückführen',
      'Eine Psychologin empfehlen und das Gespräch für beendet erklären',
      'Die eigenen Gefühle ebenfalls offenbaren, um Nähe herzustellen',
    ],
    korrektIndex: 1,
    erklaerung: 'Mitgefühl zeigen ist richtig und wichtig – aber die Lehrkraft ist keine Therapeutin. Die Kunst liegt darin, Verständnis zu signalisieren, ohne die Gesprächsführung abzugeben. Eine Erziehungsberatungsstelle könnte als Hinweis gegeben werden – aber das Kind als Thema sollte im Zentrum bleiben.',
  },
]

// ─── Hilfsfunktion: Fragen nach Modul + Schwierigkeit filtern ─────────────────

export function getFragenFuerModul(modul: QuizModul, schwierigkeit?: Schwierigkeit): QuizFrage[] {
  return QUIZ_FRAGEN.filter(
    f => f.modul === modul && (!schwierigkeit || f.schwierigkeit === schwierigkeit)
  )
}

export function getAllFragenFuerSchwierigkeit(schwierigkeit: Schwierigkeit): QuizFrage[] {
  return QUIZ_FRAGEN.filter(f => f.schwierigkeit === schwierigkeit)
}
